name: Publish

on:
  push:
    tags:
      - 'v*'   # triggers only on version tags like v0.0.3

permissions:
  contents: read
  packages: write   # required for npm publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org/'

      - run: npm ci

      # Navigate to the library folder
      - run: cd libs/core && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}